/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LAT4;

/**
 *
 * @author alvin
 */
public class latihan4 extends javax.swing.JFrame {

    /**
     * Creates new form latihan4
     */
    public latihan4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Kelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TKJ = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        RPL = new javax.swing.JRadioButton();
        Designer = new javax.swing.JCheckBox();
        programming = new javax.swing.JCheckBox();
        Animator = new javax.swing.JCheckBox();
        teknisi = new javax.swing.JCheckBox();
        Submit = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Data isian");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(172, 23, 90, 14);

        jLabel2.setText("Jurusan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 120, 60, 14);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(135, 48, 100, 20);

        jLabel3.setText("Kelas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(46, 86, 80, 14);

        Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasActionPerformed(evt);
            }
        });
        getContentPane().add(Kelas);
        Kelas.setBounds(135, 86, 100, 20);

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(46, 51, 60, 14);

        buttonGroup1.add(TKJ);
        TKJ.setText("TKJ");
        getContentPane().add(TKJ);
        TKJ.setBounds(180, 120, 43, 23);

        jLabel5.setText("Jurusan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 120, 60, 14);

        buttonGroup1.add(RPL);
        RPL.setText("RPL");
        getContentPane().add(RPL);
        RPL.setBounds(110, 120, 43, 23);

        Designer.setText("Designer");
        getContentPane().add(Designer);
        Designer.setBounds(210, 170, 130, 23);

        programming.setText("Programming");
        getContentPane().add(programming);
        programming.setBounds(110, 150, 100, 23);

        Animator.setText("Animator");
        getContentPane().add(Animator);
        Animator.setBounds(110, 170, 130, 23);

        teknisi.setText("Teknisi");
        getContentPane().add(teknisi);
        teknisi.setBounds(210, 150, 130, 23);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(40, 210, 65, 23);

        Exit.setText("Exit");
        getContentPane().add(Exit);
        Exit.setBounds(230, 210, 65, 23);

        Hapus.setText("Hapus");
        getContentPane().add(Hapus);
        Hapus.setBounds(140, 210, 63, 23);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 280, 330, 150);

        jLabel6.setText("Hobi");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 150, 21, 14);

        jLabel7.setText("Hasil");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 250, 22, 14);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 480);

        setSize(new java.awt.Dimension(517, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelasActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String nama= Nama.getText();
        String kelas= Kelas.getText();
        String jurusan;
        String hobi="";
        
        if (RPL.isSelected())
            jurusan = "RPL";
        else if(TKJ.isSelected())
                jurusan ="TKJ";
        else jurusan = "";
        
        if(programming.isSelected())
            hobi+=programming.getText()+",";
        else if(Animator.isSelected())
            hobi+=Animator.getText()+",";
        else if(teknisi.isSelected())
            hobi+=teknisi.getText()+",";
        else if(Designer.isSelected())
            hobi+=Designer  .getText()+",";
        else hobi="";
        
        Hasil.setText("Nama Siswa = "+nama+"\n Kelas = "+kelas+"\n jurusan = "
                +jurusan+"\n Hobi = "+hobi);
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Animator;
    private javax.swing.JCheckBox Designer;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JTextField Kelas;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton RPL;
    private javax.swing.JButton Submit;
    private javax.swing.JRadioButton TKJ;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox programming;
    private javax.swing.JCheckBox teknisi;
    // End of variables declaration//GEN-END:variables
}
